### ISSUE TITLE
Update Red Hat "shadowman" logo for oAuth page

### ISSUE THREAD

**Issue by bmicklea** [codenvy/redhat#18]
The shadowman logo I created uses inverted colors. Please replace it with the version attached here:

![logo_rh_bw_rgb_default](https://cloud.githubusercontent.com/assets/7644938/26262702/a72c3e48-3ca3-11e7-98cd-a257fb4ec295.png)

**Comment by vkuznyetsov** [comment]
@bmicklea please make it more clear to me:
- should we replace the logo for ouath button in login page?
![red hat login](https://cloud.githubusercontent.com/assets/2101815/26297334/167ced72-3edb-11e7-86f9-d7655717e6c6.png)

**Comment by bmicklea** [comment]
Yes, correct - that's the button that has to be changed. They want to start the beta program tomorrow or Wednesday so please commit the fix today if possible.

**Comment by vkuznyetsov** [comment]
![red hat login](https://cloud.githubusercontent.com/assets/2101815/26309137/8e0f4dd4-3f04-11e7-8347-641cb198fea1.png)
Image you attached looks weird here.

**Comment by bmicklea** [comment]
It will need a white background and should be placed after the "g+" logo.

**Comment by vkuznyetsov** [comment]
![red hat new oauth](https://cloud.githubusercontent.com/assets/2101815/26357744/f5f79846-3fd8-11e7-81fe-a7d4d027e568.png)
Is it OK? Should it shaded in gray on mouse hover?

**Comment by bmicklea** [comment]
Yes please

**Comment by vkuznyetsov** [comment]
done
redhat.codenvy.com updated
