### ISSUE TITLE
Targeted line in action must be shown at the top of the editor

### ISSUE THREAD

**Issue by slemeur** [codenvy/redhat#35]
Feedback from #30.

We introduced the ability to target a particular line of the editor with an action.

**Current Behaviour:**
The line is sometime displayed at the top of the editor and sometime down which makes it difficult to catch.

**Expected Behaviour:**
When we are calling this action, we need to display the line at the top of the editor.

**Comment by tolusha** [comment]
https://github.com/eclipse/che/issues/6330
