### ISSUE TITLE
Automatically redirect to developers.redhat.com authentication

### ISSUE THREAD

**Issue by slemeur** [codenvy/redhat#50]
Today, when someone is using the `try-it-now` factory for `jboss-eap` he needs to be authenticate on redhat.codenvy.com and for that we redirect him to the following page:
![screen shot 2017-09-29 at 14 34 29](https://user-images.githubusercontent.com/1636769/31016027-5944426e-a523-11e7-99dd-1a7df8c46f84.png)

We would like to avoid this and only redirect the user to the "redhat authentication flow" which is accessed by the user when he is clicking on the "redhat" button.

![screen shot 2017-09-29 at 14 38 29](https://user-images.githubusercontent.com/1636769/31016147-e045e34e-a523-11e7-88a1-37ba29c81cbb.png)

**The new flow would be the following:**
- user consuming a factory: we detect if he is authenticated or not
- if authenticate, we let the user using the factory and getting his workspace
- if not authenticated, we redirect the user to the redhat authentication/registration flow.

**Comment by tolusha** [comment]
@slemeur 
If so, we have to remove Google and GitHub login buttons

**Comment by slemeur** [comment]
Yes we don't need them anymore
